base_url = "https://www.saucedemo.com/"
products_url = f"{base_url}inventory.html"


standard_user = "standard_user"
locked_out_user = "locked_out_user"
performance_glitch_user = "performance_glitch_user"
error_user = "error_user"
visual_user ="visual_user"
correct_password = "secret_sauce"
first_name = "Test"
last_name = "Esty"
zip_code = "zipcode"
sauce_labs_onesie = "Sauce Labs Onesie"
total_3_price = "53.97"
total_2_price = "37.98"
onesie_price = "7.99"
backpack_price = "29.99"